cf_dashboard/config/routes.rb
CfDashboard::Application.routes.draw do
  #devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    # get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  match 'profile' => 'profile#index'
  match 'profile/answers' => 'profile#answers'

  root :to => "home#index"

  resources :questions do
    
    collection do
      get 'my' 
      get 'my_open'
      get 'all_open'
      get 'unassigned'
      get 'unanswered'
      get 'search'

      get 'more'
      get 'questions_for_day'
      get 'questions_for_week'
      get 'questions_for_month'
    end

    resources :answers
    resources :assignments
  end
  
  resources :answers
  
end

cf_dashboard/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_filter :init

  def index
    @all_assigned_questions = Assignment.assignment_table
    all_question_ids = @all_assigned_questions.keys.join ";"

    @questions = @so_client.questions?(:tagged => 'cloudfoundry', :filter => 'withbody', :order => 'desc', :sort => 'creation', :pagesize => 20, :page => @page)["items"]

    render_questions
  end

  def my
    @assigned_questions = current_user.nil? ? {} : current_user.assigned_questions
    users_question_ids = @assigned_questions.keys.join ";"

    @all_assigned_questions = Assignment.assignment_table
    all_question_ids = @all_assigned_questions.keys.join ";"

    # so list of users questions
    @questions = @assigned_questions.length > 0 ? @so_client.questions_ids?(:filter => 'withbody', :order => 'desc', :sort => 'creation', :pagesize => 20, :page => @page, :ids => users_question_ids)["items"] : []

    render_questions

  end

  def all_open
    @assigned_questions = current_user.nil? ? {} : current_user.open_assigned_questions
    users_question_ids = @assigned_questions.keys.join ";"

    @all_assigned_questions = Assignment.open_assignment_table
    all_question_ids = @all_assigned_questions.keys.join ";"

    # so list of users questions
    @questions = @all_assigned_questions.length > 0 ? @so_client.questions_ids?(:filter => 'withbody', :order => 'desc', :sort => 'creation', :pagesize => 20, :page => @page, :ids => all_question_ids)["items"] : []
    render_questions
  end

  def my_open
    @assigned_questions = current_user.nil? ? {} : current_user.open_assigned_questions
    users_question_ids = @assigned_questions.keys.join ";"

    @all_assigned_questions = Assignment.assignment_table
    all_question_ids = @all_assigned_questions.keys.join ";"

    # so list of users questions
    @questions = @assigned_questions.length > 0 ? @so_client.questions_ids?(:filter => 'withbody', :order => 'desc', :sort => 'creation', :pagesize => 20, :page => @page, :ids => users_question_ids)["items"] : []
    render_questions
  end

  def unassigned
    @all_assigned_questions = Assignment.assignment_table
    all_question_ids = @all_assigned_questions.keys.join ";"

    @questions = @so_client.questions?(:tagged => 'cloudfoundry', :filter => 'withbody', :order => 'desc', :sort => 'creation', :pagesize => 20, :page => @page)["items"]

    @questions.reject! { |q| @all_assigned_questions.has_key? q["question_id"].to_s }
    render_questions
  end

  def unanswered
    @all_assigned_questions = Assignment.assignment_table
    all_question_ids = @all_assigned_questions.keys.join ";"

    @questions = @so_client.questions_unanswered?(:tagged => 'cloudfoundry', :filter => 'withbody', :order => 'desc', :sort => 'creation', :pagesize => 20, :page => @page)["items"]

    render_questions
  end

  def search
    @all_assigned_questions = Assignment.assignment_table
    all_question_ids = @all_assigned_questions.keys.join ";"

    @questions = @so_client.search?(:tagged => 'cloudfoundry', :filter => 'withbody', :order => 'desc', :sort => 'creation', :intitle => params[:q], :pagesize => 20, :page => @page)["items"]

    render_questions
  end

  def action_missing(meth, *args, &block)
    if meth.to_s =~ /^questions_for_(.+)$/
      puts "getting #{$1}"  
      @questions = tagged_questions_for_span($1.to_sym)

      respond_to do |format|
        format.html { render :text => @questions.count }
        format.json { render :json => @questions }
      end
    else
      super
    end
  end

  def tagged_questions_for_span(span_type) # :day, :week, :month
    start_of_day = Time.now.beginning_of_day
    epoch = span_type == :day ? start_of_day.to_i : (start_of_day - (1.send(span_type))).to_i

    so_client = StackOverflowClient.new_with_oauth session["oauth_creds"]

    so_client.questions?(:tagged => 'cloudfoundry', :filter => 'withbody', :fromdate => epoch, :pagesize => 100)["items"]
  end

  def show
    
    so_client = StackOverflowClient.new_with_oauth session["oauth_creds"]
    @question = so_client.instance_eval("questions_#{params[:id]}? :filter => 'withbody'")["items"].first
    @comments = so_client.instance_eval("questions_#{params[:id]}_comments? :filter => 'withbody'")["items"]

    # find assignment
    @assignment = Assignment.find_by_question_id(params[:id]) || Assignment.new
    note = @assignment.notes.build

    respond_to do |format|
      format.html
      format.json { render :json => @question }
    end

  end

  private

  def init
    @page = params[:page] || 1
    @so_client = StackOverflowClient.new_with_oauth session["oauth_creds"]
  end

  def render_questions
    respond_to do |format|
      format.html { 
        if @page == 1
          render 'question_results'
        else
          render :partial => 'questions', :locals => { :questions => @questions, :assigned_questions => @all_assigned_questions, :do_load_lock => true }
        end
      }
      format.json { render :json => @questions }
    end
  end
end

cf_dashboard/app/helpers/questions_helper.rb
module QuestionsHelper
  def status_class_for_question(question)
    return "complete" if question["is_answered"] == true
    return "has-answers" if question["is_answered"] == false and question["answer_count"] > 0
    return "unanswered" if question["is_answered"] == false and question["answer_count"] == 0
  end
end

cf_dashboard/app/views/questions/_questions.html.erb
<% do_locking = do_load_lock || false %>
<% closed = assigned_questions.select { |x,y| y.status == 'Closed' } %>

<% questions.each do |question| %>
  <li class="subnav question-row">
    <div class="row">
      <div class="span1 status-tab <%= status_class_for_question(question) %>">

      </div>
      <div class="span10">
        <span class="lead small"><a data-content="<%= question["body"] %>" rel="popover" href="/questions/<%= question["question_id"] %>"><%= question["title"].html_safe %></a></span>

        <% if assigned_questions.has_key?(question["question_id"].to_s) %>
          <% if not assigned_questions[question["question_id"].to_s].user_id.nil? %><span class="pull-right">
            <img src="<%= assigned_questions[question["question_id"].to_s].user.profile_image %>">
          </span>

          <% if not assigned_questions[question["question_id"].to_s].status.empty? %><span class="label label-important pull-right"><%= assigned_questions[question["question_id"].to_s].status %></span><% end %>
          <% if not assigned_questions[question["question_id"].to_s].priority.empty? %><span class="label label-important pull-right"><%= assigned_questions[question["question_id"].to_s].priority %></span><% end %>
        <% end %>

        <% end %>
        <br>
        <span class="created-date"><%= Time.at(question["creation_date"]).strftime("%Y-%m-%d %H:%M %Z") %></span>
      </div>
    </div>
  </li>
<% end %>

<% if do_locking %>
  <% if questions.length < 20 %>
    <script>window.load_lock = true;</script>
  <% else %>
    <script>window.load_lock = false;</script>
  <% end %>
<% end %>

cf_dashboard/app/views/questions/index.html.erb
<h2>All open questions</h2>
<ul id="open-questions">
  <%= render :partial => 'questions', :locals => { :questions => @all_questions, :assigned_questions => @all_assigned_questions, :do_load_lock => true} %>
</ul>

<span id="loading-more"><center><h2>Loading more questions ... </h2></center><br></span>
<script language="javascript">$(document).ready(function(){ init_load_on_scroll(); });</script>

cf_dashboard/app/views/questions/question_results.html.erb
<h3><%= @questions.length %> results found.</h3>
<ul id="questions">
  <%= render :partial => 'questions', :locals => { :questions => @questions, :assigned_questions => @all_assigned_questions, :do_load_lock => true} %>
</ul>

<span id="loading-more"><center><h2>Loading more questions ... </h2></center><br></span>
<script language="javascript">$(document).ready(function(){ init_load_on_scroll();  });</script>

cf_dashboard/app/views/questions/show.html.erb
<% form_path = @assignment.id.nil? ? question_assignments_path(params[:id]) : question_assignment_path(params[:id], @assignment.id) %>

<%= form_for @assignment, :url => form_path, :class => "form-horizontal" do |form| %>
<div class="row">
  <div class="span8">
    <h2><%= @question["title"].html_safe %></h2>
    Stack Overflow&nbsp;<a title="View on Stackoverflow.com" target="_blank" href="<%= @question["link"] %>" class="icon-share"></a>
    <% if not @assignment.jira_id.nil? %>
    <% if not @assignment.jira_id.empty? %>Jira&nbsp;<a title="View on Jira" target="_blank" href="https://rubicon.atlassian.net/browse/<%= @assignment.jira_id %>" class="icon-share"></a><% end %>
    <% end %>
    <% if not @assignment.zendesk_id.nil? %>
    <% if not @assignment.zendesk_id.empty? %>Zendesk&nbsp;<a title="View on Zendesk" target="_blank" href="http://support.cloudfoundry.com/tickets/<%= @assignment.zendesk_id %>" class="icon-share"></a><% end %>
    <% end %>
    <br><br>
    <%= @question["body"].html_safe %>

    <% @comments.each do |comment| %>
      <div class="row comment">
        <div class="span6">
          <span>
            <%= comment["body"].html_safe %>
          </span>
        </div>
        <div class="span2">
          <span>
            <cite>
          - <%= comment["owner"]["display_name"] %><br />
            <%= Time.at(comment["creation_date"]).strftime("%Y-%m-%d %H:%M") %>
          </cite>
          </span>
        </div>
      </div>

    <% end %>
  </div>
  <div class="span4">
    <div class="well" id="manage-questions">
      Date created : <%= Time.at(@question["creation_date"]).strftime("%Y-%m-%d %H:%M %Z") %><br>
      <% if not @question["last_edit_date"].nil? %>
        Date updated : <%= Time.at(@question["last_edit_date"]).strftime("%Y-%m-%d %H:%M %Z") %>
      <% end %>

        <fieldset>
          <legend>Manage question</legend>

          <div class="control-group question-management">

            <div class="row">
              <div class="span1">
                <label class="control-label" for="optionsCheckbox">Owner</label>
              </div>
              <div class="span2  pull-right">
                <div class="controls">
                  <%= form.select(:user_id, User.all.collect {|p| [ p.display_name, p.id ] }, {:prompt => 'Select User'} ) %>
                </div>
              </div>
            </div>

            <br>
            <div class="row">
              <div class="span1">
                <label class="control-label" for="optionsCheckbox">Priority</label>
              </div>
              <div class="span2 pull-right">
                <div class="controls">
                  <%= form.select(:priority, %w{High Medium Low}, {:prompt => 'Select Priority'} ) %>
                </div>
              </div>
            </div>

            <br>
            <div class="row">
              <div class="span1">
                <label class="control-label" for="optionsCheckbox">Status</label>
              </div>
              <div class="span2 pull-right">
                <div class="controls">
                  <%= form.select(:status, %w{Open Pending Closed}, {:prompt => 'Select Status'} ) %>
                </div>
              </div>
            </div>

            <br>
            <div class="row">
              <div class="span1">
                <label class="control-label" for="optionsCheckbox">Jira ID</label>
              </div>
              <div class="span2 pull-right">
                <div class="controls">
                  <%= form.text_field(:jira_id) %>
                </div>
              </div>
            </div>

            <br>
            <div class="row">
              <div class="span1">
                <label class="control-label" for="optionsCheckbox">Zendesk ID</label>
              </div>
              <div class="span2 pull-right">
                <div class="controls">
                  <%= form.text_field(:zendesk_id) %>
                </div>
              </div>
            </div>
          </div>

          <div class="form-actions">
            <% if not current_user.nil? %><button type="submit" class="btn btn-primary">Save changes</button><% end %>
          </div>
        </fieldset>

    </div>
  </div>
</div>

  <div class="row">
    <div class="span12">
      <div class="well">
        <h4><%= @question["answer_count"] %> answers. <a id="load-answers" href="#">Show</a></h4>
        <div id="answers"></div>
      </div>
    </div>
  </div>

  <h2>Notes</h2>

  <% @assignment.notes.reverse_order.each do |note| %>
    <% if not note.new_record? %>
      <div class="well">
        <div class="row">
          <div class="span2 profile">
            <% if not note.user.nil? %>
              <img src="<%= note.user.profile_image %>"><br>
              <%= note.user.display_name %>
            <% end %>
          </div>
          <div class="span9">

            <% if note.user_id == current_user.id %>
              <div class="note">
                <div class="note-edit">
                <%= form.fields_for :notes, note do |note_form| %>
                  <%= note_form.hidden_field :user_id, :value => current_user.id %>
                  <%= note_form.text_area :content, :cols=>180, :rows=>5, :class=>'note-content' %>
                <% end %>
                </div>

                <div class="edit-switch pull-right"><a href="#">Edit</a></div>
              </div>
            <% end %>

            <pre class="note"><%= note.content %></pre>
            <span class="pull-right"><%= note.created_at %></span>

          </div>

        </div>
      </div>
    <% end %>
  <% end %>
  <% if not current_user.nil? %>
    <h3>Add new note</h3>
    <%= form.fields_for :notes do |note_form| %>

      <% if note_form.object.new_record? %>
        <%= note_form.hidden_field :user_id, :value => current_user.id %>
        <%= note_form.text_area :content, :cols=>180, :rows=>5, :class=>'note-content' %>
      <% end %>
    <% end %>

    <button type="submit" class="btn btn-primary">Save changes</button>
  <% end %>
<% end %>